"""
Gemini compatibility patch for upskill.

Applies two fixes to the installed upskill package so it works with Google Gemini:

Fix 1 — Agent card model (upskill/agent_cards/test_gen.md)
  The released package has the test generator hardcoded to Anthropic Opus.
  This replaces it with google.gemini-2.5-pro.

Fix 2 — JSON schema (upskill/models.py)
  Gemini rejects schemas with 'additionalProperties' (generated by Pydantic
  for dict[str, ...] fields). This strips that key so structured output works.

Run once after installing upskill:
    python patch.py
"""

import importlib.util
import sys
from pathlib import Path

GEMINI_MODEL = "google.gemini-2.5-pro"
PATCH_MARKER = "# [gemini-patch]"

NEW_LINES = f"""\
{PATCH_MARKER} — strip additionalProperties for Gemini structured output compatibility
from typing import Any as _Any


def _strip_additional_properties(schema: dict[str, _Any]) -> None:
    \"\"\"Recursively remove additionalProperties from a JSON schema in-place.\"\"\"
    schema.pop("additionalProperties", None)
    for value in schema.values():
        if isinstance(value, dict):
            _strip_additional_properties(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    _strip_additional_properties(item)

"""

TEST_CASE_SUITE_PATCH = f"""\
    @classmethod
    def model_json_schema(cls, **kwargs: _Any) -> dict[str, _Any]:  {PATCH_MARKER}
        schema: dict[str, _Any] = super().model_json_schema(**kwargs)
        _strip_additional_properties(schema)
        return schema
"""


def find_package_dir() -> Path:
    spec = importlib.util.find_spec("upskill.models")
    if spec is None or spec.origin is None:
        print("ERROR: upskill is not installed.")
        print("  Run: pip install upskill")
        sys.exit(1)
    return Path(spec.origin).parent


# ── Fix 1: agent card ─────────────────────────────────────────────────────────

def patch_agent_cards(package_dir: Path) -> None:
    """Replace hardcoded Anthropic model in test_gen.md with Gemini."""
    card_path = package_dir / "agent_cards" / "test_gen.md"
    if not card_path.exists():
        print(f"WARNING: Agent card not found at {card_path} — skipping.")
        return

    content = card_path.read_text(encoding="utf-8")

    if GEMINI_MODEL in content:
        print(f"Agent card already patched: {card_path}")
        return

    # Replace any hardcoded model line (e.g. 'model: opus?reasoning=1024')
    lines = content.splitlines(keepends=True)
    new_lines = []
    patched = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("model:") and not stripped.startswith("#"):
            new_lines.append(f"model: {GEMINI_MODEL}  {PATCH_MARKER}\n")
            patched = True
        else:
            new_lines.append(line)

    if not patched:
        # No model line existed — insert one after the opening ---
        result = []
        in_frontmatter = False
        inserted = False
        for line in new_lines:
            result.append(line)
            if line.strip() == "---" and not inserted:
                if not in_frontmatter:
                    in_frontmatter = True
                else:
                    result.insert(-1, f"model: {GEMINI_MODEL}  {PATCH_MARKER}\n")
                    inserted = True
        new_lines = result

    card_path.write_text("".join(new_lines), encoding="utf-8")
    print(f"Patched agent card: {card_path}")


# ── Fix 2: JSON schema ────────────────────────────────────────────────────────

def patch_models_file(package_dir: Path) -> None:
    """Strip additionalProperties from TestCaseSuite JSON schema."""
    path = package_dir / "models.py"
    if not path.exists():
        print(f"ERROR: models.py not found at {path}")
        sys.exit(1)

    original = path.read_text(encoding="utf-8")

    if PATCH_MARKER in original or "_strip_additional_properties" in original:
        print(f"models.py already patched: {path}")
        return

    insert_before = "\nclass SkillMetadata"
    if insert_before not in original:
        print("ERROR: Could not find insertion point in models.py.")
        print("  The upskill version may have changed. Please open an issue.")
        sys.exit(1)

    patched = original.replace(insert_before, f"\n{NEW_LINES}class SkillMetadata", 1)

    suite_marker = "    cases: list[TestCase] = Field(default_factory=list)"
    if suite_marker not in patched:
        print("ERROR: Could not find TestCaseSuite.cases field in models.py.")
        sys.exit(1)

    patched = patched.replace(
        suite_marker,
        f"{suite_marker}\n\n{TEST_CASE_SUITE_PATCH}",
        1,
    )

    backup = path.with_suffix(".py.bak")
    backup.write_text(original, encoding="utf-8")
    print(f"Backup saved:       {backup}")
    path.write_text(patched, encoding="utf-8")
    print(f"Patched models.py:  {path}")


# ── main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    package_dir = find_package_dir()
    print(f"Found upskill package at: {package_dir}")
    print()
    patch_agent_cards(package_dir)
    patch_models_file(package_dir)
    print()
    print("Done. upskill is now compatible with Google Gemini.")
  
